/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppLocationsRouteImport } from './routes/_app.locations'
import { Route as AppEquipmentRouteImport } from './routes/_app.equipment'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSessionsIndexRouteImport } from './routes/_app.sessions.index'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app.onboarding.index'
import { Route as AppMembersIndexRouteImport } from './routes/_app.members.index'
import { Route as AppEquipmentIndexRouteImport } from './routes/_app.equipment.index'
import { Route as AppSettingsTemplatesRouteImport } from './routes/_app.settings_.templates'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings_.roles'
import { Route as AppSessionsNewRouteImport } from './routes/_app.sessions.new'
import { Route as AppOnboardingProfileRouteImport } from './routes/_app.onboarding.profile'
import { Route as AppOnboardingCompleteRouteImport } from './routes/_app.onboarding.complete'
import { Route as AppOnboardingCoachRouteImport } from './routes/_app.onboarding.coach'
import { Route as AppMembersMemberIdRouteImport } from './routes/_app.members.$memberId'
import { Route as AppEquipmentFaultsRouteImport } from './routes/_app.equipment.faults'
import { Route as AppEquipmentEquipmentIdRouteImport } from './routes/_app.equipment.$equipmentId'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin_.audit'
import { Route as AppSessionsSessionIdIndexRouteImport } from './routes/_app.sessions.$sessionId.index'
import { Route as AppMembersMemberIdIndexRouteImport } from './routes/_app.members.$memberId.index'
import { Route as AppEquipmentListsIndexRouteImport } from './routes/_app.equipment.lists.index'
import { Route as AppSessionsSessionIdEditRouteImport } from './routes/_app.sessions.$sessionId.edit'
import { Route as AppSessionsSessionIdCarpoolRouteImport } from './routes/_app.sessions.$sessionId.carpool'
import { Route as AppMembersMemberIdEditRouteImport } from './routes/_app.members.$memberId.edit'
import { Route as AppEquipmentListsNewRouteImport } from './routes/_app.equipment.lists.new'
import { Route as AppEquipmentListsListIdPackRouteImport } from './routes/_app.equipment.lists.$listId.pack'
import { Route as AppEquipmentListsListIdEditRouteImport } from './routes/_app.equipment.lists.$listId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSessionsRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentIndexRoute = AppEquipmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEquipmentRoute,
} as any)
const AppSettingsTemplatesRoute = AppSettingsTemplatesRouteImport.update({
  id: '/settings_/templates',
  path: '/settings/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings_/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSessionsRoute,
} as any)
const AppOnboardingProfileRoute = AppOnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingCompleteRoute = AppOnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingCoachRoute = AppOnboardingCoachRouteImport.update({
  id: '/onboarding/coach',
  path: '/onboarding/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersMemberIdRoute = AppMembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentFaultsRoute = AppEquipmentFaultsRouteImport.update({
  id: '/faults',
  path: '/faults',
  getParentRoute: () => AppEquipmentRoute,
} as any)
const AppEquipmentEquipmentIdRoute = AppEquipmentEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => AppEquipmentRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin_/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdIndexRoute =
  AppSessionsSessionIdIndexRouteImport.update({
    id: '/$sessionId/',
    path: '/$sessionId/',
    getParentRoute: () => AppSessionsRoute,
  } as any)
const AppMembersMemberIdIndexRoute = AppMembersMemberIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMembersMemberIdRoute,
} as any)
const AppEquipmentListsIndexRoute = AppEquipmentListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppEquipmentRoute,
} as any)
const AppSessionsSessionIdEditRoute =
  AppSessionsSessionIdEditRouteImport.update({
    id: '/$sessionId/edit',
    path: '/$sessionId/edit',
    getParentRoute: () => AppSessionsRoute,
  } as any)
const AppSessionsSessionIdCarpoolRoute =
  AppSessionsSessionIdCarpoolRouteImport.update({
    id: '/$sessionId/carpool',
    path: '/$sessionId/carpool',
    getParentRoute: () => AppSessionsRoute,
  } as any)
const AppMembersMemberIdEditRoute = AppMembersMemberIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppMembersMemberIdRoute,
} as any)
const AppEquipmentListsNewRoute = AppEquipmentListsNewRouteImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => AppEquipmentRoute,
} as any)
const AppEquipmentListsListIdPackRoute =
  AppEquipmentListsListIdPackRouteImport.update({
    id: '/lists/$listId/pack',
    path: '/lists/$listId/pack',
    getParentRoute: () => AppEquipmentRoute,
  } as any)
const AppEquipmentListsListIdEditRoute =
  AppEquipmentListsListIdEditRouteImport.update({
    id: '/lists/$listId/edit',
    path: '/lists/$listId/edit',
    getParentRoute: () => AppEquipmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipment': typeof AppEquipmentRouteWithChildren
  '/locations': typeof AppLocationsRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/equipment/$equipmentId': typeof AppEquipmentEquipmentIdRoute
  '/equipment/faults': typeof AppEquipmentFaultsRoute
  '/members/$memberId': typeof AppMembersMemberIdRouteWithChildren
  '/onboarding/coach': typeof AppOnboardingCoachRoute
  '/onboarding/complete': typeof AppOnboardingCompleteRoute
  '/onboarding/profile': typeof AppOnboardingProfileRoute
  '/sessions/new': typeof AppSessionsNewRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/equipment/': typeof AppEquipmentIndexRoute
  '/members/': typeof AppMembersIndexRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/equipment/lists/new': typeof AppEquipmentListsNewRoute
  '/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/sessions/$sessionId/carpool': typeof AppSessionsSessionIdCarpoolRoute
  '/sessions/$sessionId/edit': typeof AppSessionsSessionIdEditRoute
  '/equipment/lists/': typeof AppEquipmentListsIndexRoute
  '/members/$memberId/': typeof AppMembersMemberIdIndexRoute
  '/sessions/$sessionId/': typeof AppSessionsSessionIdIndexRoute
  '/equipment/lists/$listId/edit': typeof AppEquipmentListsListIdEditRoute
  '/equipment/lists/$listId/pack': typeof AppEquipmentListsListIdPackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/attendance': typeof AppAttendanceRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/locations': typeof AppLocationsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/equipment/$equipmentId': typeof AppEquipmentEquipmentIdRoute
  '/equipment/faults': typeof AppEquipmentFaultsRoute
  '/onboarding/coach': typeof AppOnboardingCoachRoute
  '/onboarding/complete': typeof AppOnboardingCompleteRoute
  '/onboarding/profile': typeof AppOnboardingProfileRoute
  '/sessions/new': typeof AppSessionsNewRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/equipment': typeof AppEquipmentIndexRoute
  '/members': typeof AppMembersIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/equipment/lists/new': typeof AppEquipmentListsNewRoute
  '/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/sessions/$sessionId/carpool': typeof AppSessionsSessionIdCarpoolRoute
  '/sessions/$sessionId/edit': typeof AppSessionsSessionIdEditRoute
  '/equipment/lists': typeof AppEquipmentListsIndexRoute
  '/members/$memberId': typeof AppMembersMemberIdIndexRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdIndexRoute
  '/equipment/lists/$listId/edit': typeof AppEquipmentListsListIdEditRoute
  '/equipment/lists/$listId/pack': typeof AppEquipmentListsListIdPackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/equipment': typeof AppEquipmentRouteWithChildren
  '/_app/locations': typeof AppLocationsRoute
  '/_app/sessions': typeof AppSessionsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin_/audit': typeof AppAdminAuditRoute
  '/_app/equipment/$equipmentId': typeof AppEquipmentEquipmentIdRoute
  '/_app/equipment/faults': typeof AppEquipmentFaultsRoute
  '/_app/members/$memberId': typeof AppMembersMemberIdRouteWithChildren
  '/_app/onboarding/coach': typeof AppOnboardingCoachRoute
  '/_app/onboarding/complete': typeof AppOnboardingCompleteRoute
  '/_app/onboarding/profile': typeof AppOnboardingProfileRoute
  '/_app/sessions/new': typeof AppSessionsNewRoute
  '/_app/settings_/roles': typeof AppSettingsRolesRoute
  '/_app/settings_/templates': typeof AppSettingsTemplatesRoute
  '/_app/equipment/': typeof AppEquipmentIndexRoute
  '/_app/members/': typeof AppMembersIndexRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/equipment/lists/new': typeof AppEquipmentListsNewRoute
  '/_app/members/$memberId/edit': typeof AppMembersMemberIdEditRoute
  '/_app/sessions/$sessionId/carpool': typeof AppSessionsSessionIdCarpoolRoute
  '/_app/sessions/$sessionId/edit': typeof AppSessionsSessionIdEditRoute
  '/_app/equipment/lists/': typeof AppEquipmentListsIndexRoute
  '/_app/members/$memberId/': typeof AppMembersMemberIdIndexRoute
  '/_app/sessions/$sessionId/': typeof AppSessionsSessionIdIndexRoute
  '/_app/equipment/lists/$listId/edit': typeof AppEquipmentListsListIdEditRoute
  '/_app/equipment/lists/$listId/pack': typeof AppEquipmentListsListIdPackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/attendance'
    | '/chat'
    | '/dashboard'
    | '/equipment'
    | '/locations'
    | '/sessions'
    | '/settings'
    | '/admin/audit'
    | '/equipment/$equipmentId'
    | '/equipment/faults'
    | '/members/$memberId'
    | '/onboarding/coach'
    | '/onboarding/complete'
    | '/onboarding/profile'
    | '/sessions/new'
    | '/settings/roles'
    | '/settings/templates'
    | '/equipment/'
    | '/members/'
    | '/onboarding/'
    | '/sessions/'
    | '/equipment/lists/new'
    | '/members/$memberId/edit'
    | '/sessions/$sessionId/carpool'
    | '/sessions/$sessionId/edit'
    | '/equipment/lists/'
    | '/members/$memberId/'
    | '/sessions/$sessionId/'
    | '/equipment/lists/$listId/edit'
    | '/equipment/lists/$listId/pack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/attendance'
    | '/chat'
    | '/dashboard'
    | '/locations'
    | '/settings'
    | '/admin/audit'
    | '/equipment/$equipmentId'
    | '/equipment/faults'
    | '/onboarding/coach'
    | '/onboarding/complete'
    | '/onboarding/profile'
    | '/sessions/new'
    | '/settings/roles'
    | '/settings/templates'
    | '/equipment'
    | '/members'
    | '/onboarding'
    | '/sessions'
    | '/equipment/lists/new'
    | '/members/$memberId/edit'
    | '/sessions/$sessionId/carpool'
    | '/sessions/$sessionId/edit'
    | '/equipment/lists'
    | '/members/$memberId'
    | '/sessions/$sessionId'
    | '/equipment/lists/$listId/edit'
    | '/equipment/lists/$listId/pack'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/admin'
    | '/_app/attendance'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/equipment'
    | '/_app/locations'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/admin_/audit'
    | '/_app/equipment/$equipmentId'
    | '/_app/equipment/faults'
    | '/_app/members/$memberId'
    | '/_app/onboarding/coach'
    | '/_app/onboarding/complete'
    | '/_app/onboarding/profile'
    | '/_app/sessions/new'
    | '/_app/settings_/roles'
    | '/_app/settings_/templates'
    | '/_app/equipment/'
    | '/_app/members/'
    | '/_app/onboarding/'
    | '/_app/sessions/'
    | '/_app/equipment/lists/new'
    | '/_app/members/$memberId/edit'
    | '/_app/sessions/$sessionId/carpool'
    | '/_app/sessions/$sessionId/edit'
    | '/_app/equipment/lists/'
    | '/_app/members/$memberId/'
    | '/_app/sessions/$sessionId/'
    | '/_app/equipment/lists/$listId/edit'
    | '/_app/equipment/lists/$listId/pack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/': {
      id: '/_app/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment/': {
      id: '/_app/equipment/'
      path: '/'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AppEquipmentIndexRouteImport
      parentRoute: typeof AppEquipmentRoute
    }
    '/_app/settings_/templates': {
      id: '/_app/settings_/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AppSettingsTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/roles': {
      id: '/_app/settings_/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/new': {
      id: '/_app/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/onboarding/profile': {
      id: '/_app/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AppOnboardingProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/complete': {
      id: '/_app/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof AppOnboardingCompleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/coach': {
      id: '/_app/onboarding/coach'
      path: '/onboarding/coach'
      fullPath: '/onboarding/coach'
      preLoaderRoute: typeof AppOnboardingCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/$memberId': {
      id: '/_app/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AppMembersMemberIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment/faults': {
      id: '/_app/equipment/faults'
      path: '/faults'
      fullPath: '/equipment/faults'
      preLoaderRoute: typeof AppEquipmentFaultsRouteImport
      parentRoute: typeof AppEquipmentRoute
    }
    '/_app/equipment/$equipmentId': {
      id: '/_app/equipment/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof AppEquipmentEquipmentIdRouteImport
      parentRoute: typeof AppEquipmentRoute
    }
    '/_app/admin_/audit': {
      id: '/_app/admin_/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId/': {
      id: '/_app/sessions/$sessionId/'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof AppSessionsSessionIdIndexRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/members/$memberId/': {
      id: '/_app/members/$memberId/'
      path: '/'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof AppMembersMemberIdIndexRouteImport
      parentRoute: typeof AppMembersMemberIdRoute
    }
    '/_app/equipment/lists/': {
      id: '/_app/equipment/lists/'
      path: '/lists'
      fullPath: '/equipment/lists/'
      preLoaderRoute: typeof AppEquipmentListsIndexRouteImport
      parentRoute: typeof AppEquipmentRoute
    }
    '/_app/sessions/$sessionId/edit': {
      id: '/_app/sessions/$sessionId/edit'
      path: '/$sessionId/edit'
      fullPath: '/sessions/$sessionId/edit'
      preLoaderRoute: typeof AppSessionsSessionIdEditRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/sessions/$sessionId/carpool': {
      id: '/_app/sessions/$sessionId/carpool'
      path: '/$sessionId/carpool'
      fullPath: '/sessions/$sessionId/carpool'
      preLoaderRoute: typeof AppSessionsSessionIdCarpoolRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/members/$memberId/edit': {
      id: '/_app/members/$memberId/edit'
      path: '/edit'
      fullPath: '/members/$memberId/edit'
      preLoaderRoute: typeof AppMembersMemberIdEditRouteImport
      parentRoute: typeof AppMembersMemberIdRoute
    }
    '/_app/equipment/lists/new': {
      id: '/_app/equipment/lists/new'
      path: '/lists/new'
      fullPath: '/equipment/lists/new'
      preLoaderRoute: typeof AppEquipmentListsNewRouteImport
      parentRoute: typeof AppEquipmentRoute
    }
    '/_app/equipment/lists/$listId/pack': {
      id: '/_app/equipment/lists/$listId/pack'
      path: '/lists/$listId/pack'
      fullPath: '/equipment/lists/$listId/pack'
      preLoaderRoute: typeof AppEquipmentListsListIdPackRouteImport
      parentRoute: typeof AppEquipmentRoute
    }
    '/_app/equipment/lists/$listId/edit': {
      id: '/_app/equipment/lists/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/equipment/lists/$listId/edit'
      preLoaderRoute: typeof AppEquipmentListsListIdEditRouteImport
      parentRoute: typeof AppEquipmentRoute
    }
  }
}

interface AppEquipmentRouteChildren {
  AppEquipmentEquipmentIdRoute: typeof AppEquipmentEquipmentIdRoute
  AppEquipmentFaultsRoute: typeof AppEquipmentFaultsRoute
  AppEquipmentIndexRoute: typeof AppEquipmentIndexRoute
  AppEquipmentListsNewRoute: typeof AppEquipmentListsNewRoute
  AppEquipmentListsIndexRoute: typeof AppEquipmentListsIndexRoute
  AppEquipmentListsListIdEditRoute: typeof AppEquipmentListsListIdEditRoute
  AppEquipmentListsListIdPackRoute: typeof AppEquipmentListsListIdPackRoute
}

const AppEquipmentRouteChildren: AppEquipmentRouteChildren = {
  AppEquipmentEquipmentIdRoute: AppEquipmentEquipmentIdRoute,
  AppEquipmentFaultsRoute: AppEquipmentFaultsRoute,
  AppEquipmentIndexRoute: AppEquipmentIndexRoute,
  AppEquipmentListsNewRoute: AppEquipmentListsNewRoute,
  AppEquipmentListsIndexRoute: AppEquipmentListsIndexRoute,
  AppEquipmentListsListIdEditRoute: AppEquipmentListsListIdEditRoute,
  AppEquipmentListsListIdPackRoute: AppEquipmentListsListIdPackRoute,
}

const AppEquipmentRouteWithChildren = AppEquipmentRoute._addFileChildren(
  AppEquipmentRouteChildren,
)

interface AppSessionsRouteChildren {
  AppSessionsNewRoute: typeof AppSessionsNewRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppSessionsSessionIdCarpoolRoute: typeof AppSessionsSessionIdCarpoolRoute
  AppSessionsSessionIdEditRoute: typeof AppSessionsSessionIdEditRoute
  AppSessionsSessionIdIndexRoute: typeof AppSessionsSessionIdIndexRoute
}

const AppSessionsRouteChildren: AppSessionsRouteChildren = {
  AppSessionsNewRoute: AppSessionsNewRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppSessionsSessionIdCarpoolRoute: AppSessionsSessionIdCarpoolRoute,
  AppSessionsSessionIdEditRoute: AppSessionsSessionIdEditRoute,
  AppSessionsSessionIdIndexRoute: AppSessionsSessionIdIndexRoute,
}

const AppSessionsRouteWithChildren = AppSessionsRoute._addFileChildren(
  AppSessionsRouteChildren,
)

interface AppMembersMemberIdRouteChildren {
  AppMembersMemberIdEditRoute: typeof AppMembersMemberIdEditRoute
  AppMembersMemberIdIndexRoute: typeof AppMembersMemberIdIndexRoute
}

const AppMembersMemberIdRouteChildren: AppMembersMemberIdRouteChildren = {
  AppMembersMemberIdEditRoute: AppMembersMemberIdEditRoute,
  AppMembersMemberIdIndexRoute: AppMembersMemberIdIndexRoute,
}

const AppMembersMemberIdRouteWithChildren =
  AppMembersMemberIdRoute._addFileChildren(AppMembersMemberIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipmentRoute: typeof AppEquipmentRouteWithChildren
  AppLocationsRoute: typeof AppLocationsRoute
  AppSessionsRoute: typeof AppSessionsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppMembersMemberIdRoute: typeof AppMembersMemberIdRouteWithChildren
  AppOnboardingCoachRoute: typeof AppOnboardingCoachRoute
  AppOnboardingCompleteRoute: typeof AppOnboardingCompleteRoute
  AppOnboardingProfileRoute: typeof AppOnboardingProfileRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsTemplatesRoute: typeof AppSettingsTemplatesRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipmentRoute: AppEquipmentRouteWithChildren,
  AppLocationsRoute: AppLocationsRoute,
  AppSessionsRoute: AppSessionsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppMembersMemberIdRoute: AppMembersMemberIdRouteWithChildren,
  AppOnboardingCoachRoute: AppOnboardingCoachRoute,
  AppOnboardingCompleteRoute: AppOnboardingCompleteRoute,
  AppOnboardingProfileRoute: AppOnboardingProfileRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsTemplatesRoute: AppSettingsTemplatesRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
